# Generated by Django 2.0.3 on 2018-03-22 21:12

import django.contrib.gis.db.models.fields
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={'verbose_name_plural': 'Incidences'},
        ),
        migrations.AlterModelManagers(
            name='incidences',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='incidences',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
