# Generated by Django 2.0.3 on 2018-03-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20180322_2112'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incidences',
            managers=[
            ],
        ),
    ]
